### PR TITLE
Patch UUID byte array

### PR DESCRIPTION
**Pull request by AKEOPLUS-boris-bocquet**
Dear Denikson, dear involved team,

while using your codes (btw I find them cool) for ZeroRpc client, I found that the Poller shalll be stopped rather than async stopped. Also, the server I connect the client to (which is from another project, and coded in C++) returns the UUID in byte[] rather than string. So I have a proposal to tackle this.

Hope you like it. 

Thanks in advance

Boris Bocquet

### CODE REVIEW

**Comment by denikson** [comment]
Hey, thanks for the PR. Though it's more of a one-man effort than a whole team.

The whole Poller thing is indeed a good idea. Perhaps I forgot to fix it after some testing.

As for the whole UUID thing, you need to consider that zerorpc itself doesn't impose strict rules on what a message ID object should look like.  
Most implementations of zerorpc (including the original one in Python) allow the `message_id` be either a string or a byte array, *as long as your `response_to` is of the same type when you respond*.

As an example here's a client (zerorpc-dotnet; uses string uuid) calling `strftime` from server (zerorpc-python; uses byte array uuid):
```
DEBUG:zerorpc.events:<-- <b'\x00\x80\x00\x00)'> strftime {'v': 3, 'message_id': '27f9ea22-b607-4e6e-842c-000000000000', 'response_to': None} ['%Y/%m/%d']
DEBUG:zerorpc.channel:<-- new channel 27f9ea22-b607-4e6e-842c-000000000000
DEBUG:zerorpc.events:--> <b'\x00\x80\x00\x00)'> OK {'message_id': b'847cbc5a7adb4af09c0024e8bd95dbf5', 'v': 3, 'response_to': '27f9ea22-b607-4e6e-842c-000000000000'} ('2018/08/23',)
```
As you can see, zerorpc-python respects the UUID being a string. Currently, the server in zerorpc-dotnet does the same.

While your fix will indeed work for clients, it will fail for servers because you convert all byte arrays to strings, thus not preserving the original type. Here's an example of a server (zerorpc-dotnet) with your fix trying to serve a client (zerorpc-python):

```
DEBUG:zerorpc.channel:--> new channel b'acd5509652d6420c8a447ce2ff25995e'
DEBUG:zerorpc.events:--> Echo {'message_id': b'acd5509652d6420c8a447ce2ff25995e', 'v': 3} ('hello',)
DEBUG:zerorpc.events:<-- <b''> OK {'v': 3, 'message_id': '63fa3045-dcf4-46a9-9986-000000000000', 'response_to': 'acd5509652d6420c8a447ce2ff25995e'} ['hello']
WARNING:zerorpc.channel:zerorpc.ChannelMultiplexer, unable to route event: <b''> OK {'v': 3, 'message_id': '63fa3045-dcf4-46a9-9986-000000000000', 'response_to': 'acd5509652d6420c8a447ce2ff25995e'} [...]
```
Notice that the client sent its uuid as a byte array (in `message_id`), but received it as a string (in `response_to`). This causes zerorpc to not route the response correctly, eventually causing a timeout.

All in all, if a C++ server receives `message_id` as a string, but returns it in `response_to` as a byte array, I consider it a violation of the protocol, since the original implementation of zerorpc does so too.
If I were to merge the UUID change, it would break compatibility with other zerorpc implementations -- especially the original one.

**Comment by denikson** [comment]
That's a good point; a better idea could be either returning `null` or throwing an exception in case of `message_to` (since invoking a method with an emtpy channel ID is pretty much an error, even though the proper behaviour is not documented anywhere).

**Comment by AKEOPLUS-boris-bocquet** [comment]
Dear Denikson, I coming back to yesterday problem. I rethink of the problem (that the server I use is sending back byte arrays. I though : "hey the idea is that the client has to send byte[] and then the server will answer back with byte[] and this will work".  What do you think? The problem is that this would propably give not very elegant code (or at least more complicated, because I think I will have to implement a IEqualityComparer)
intarrayaskey
 to find the key of the "channels" dictionnary. I can't just Channels.TryGetValue (because of arrays). See attachment. What is your opinion?

**Comment by denikson** [comment]
What implementation of zerorpc do you use then? Does it allow to send `message_id` as byte array as well (since it clearly receives string uuids fine)?

If so, I'm fine with replacing a string-based UUID to a byte array based one. Basically [what zerorpc-python does](https://github.com/0rpc/zerorpc-python/blob/master/zerorpc/context.py#L110) already.

Since `Guid` class already provides `ToByteArray`, it should be quite easy to implement that
.  
There should be no reason to treat ID types in any special manner, since they're just IDs used to connect messages to their respective channels.

**Comment by AKEOPLUS-boris-bocquet** [comment]
Dear Denikson,
I use a "commercial" version of a zerorpc server (developped by a third party) and the source code is saddly not available. To test my proposal (sending a byte[] in message_id) I already tricked your code so that I generated a UUID in byte[] rather than string. So this part is definitly not a problem (I could clean the code and propose it). But the problem comes latter : in SocketBase ReceiveMessage method. Finding the Channel with a byte[] key is not working properly with simply 
           Channels.TryGetValue(evt.Header.ResponseTo, out Channel ch)
See the screenshot in my previous message post.
Even if in Channels, I do have the byte[] identifier I sent, Channels.TryGetValue comparison of byte[] does not check that arrays have equal values (it very probably compares that they are the same instance). 
So I think this will lead to an implementation of a IEqualityComparer (see for instance https://stackoverflow.com/questions/14663168/an-integer-array-as-a-key-for-dictionary) and that is why I was asking your opinion.
Sorry if I was unclear in my previous post.
And btw, thank you for your responsiveness.

**Comment by denikson** [comment]
It's fine; I did eventually understand what you meant. Indeed, you would need a custom equality comparer, since arrays are inherently compared to each others by reference, and not by value.

This is, of course, not too hard to fix with a custom equality comparer. Just make sure you treat string uuids and byte array uuids properly, since the former already has a proper equality comparer and a hasher, while the latter doesn't. In the end it won't look as awful as you might think.

**Comment by AKEOPLUS-boris-bocquet** [comment]
Ok I am aligned with you. I will give a try today. See you

**Pull request closed without merging**
